apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployments/app.yaml
  - ../../base/services/app-svc.yaml
  - ../../base/ingress/app-ingress.yaml
namePrefix: stg-
commonLabels:
  env: staging
patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
