apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: platform-rules
spec:
  groups:
  - name: high-cpu-usage
    rules:
    - alert: HighCPUUsage
      expr: avg(rate(container_cpu_usage_seconds_total[2m])) > 0.8
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "High CPU usage detected"
        description: "CPU > 80% selama 2 menit"
